name: Update File

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variable
        run: echo "gc_token=${{ secrets.GC_TOKEN }}" >> $GITHUB_ENV
      
      - name: Download file
        run: |
          curl -o hustle-temp.ics "https://api.team-manager.gc.com/ics-calendar-documents/user/9eeb60a3-c8fb-4fde-9f2c-a59e214e1109.ics?teamId=8cceec49-6814-4a22-a7c9-e4e1955f810d&token=${{ env.gc_token }}"
      
      - name: Remove DTSTAMP
        run: sed -i '/^DTSTAMP:/d' hustle-temp.ics
  
      - name: Commit and push changes
        run: |
          if cmp --silent hustle-temp.ics hustle.ics; then
            echo "Files are the same"
            rm hustle-temp.ics
            exit 0
          else
            # Validate ICS file format
            if ! grep -q "^BEGIN:VCALENDAR" hustle-temp.ics || ! grep -q "^END:VCALENDAR" hustle-temp.ics; then
              echo "Invalid ICS file format - missing BEGIN:VCALENDAR or END:VCALENDAR"
              rm hustle-temp.ics
              exit 1
            fi
            
            # Check for required VEVENT components
            if ! grep -q "^BEGIN:VEVENT" hustle-temp.ics; then
              echo "Invalid ICS file format - no VEVENT components found"
              rm hustle-temp.ics
              exit 1
            fi
            
            # Validate line endings (should be CRLF for ICS files)
            if file hustle-temp.ics | grep -q "CRLF"; then
              echo "ICS file has proper CRLF line endings"
            else
              echo "Warning: ICS file may not have proper CRLF line endings"
            fi

            echo "Files are different"
            mv hustle-temp.ics hustle.ics
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add hustle.ics
            git commit -m "Update hustle.ics"
            git push
          fi
