name: Update File

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "gc_token_11u=${{ secrets.GC_TOKEN_11U }}" >> $GITHUB_ENV
          echo "gc_token_10u=${{ secrets.GC_TOKEN_10U }}" >> $GITHUB_ENV
      
      - name: Download 11U ICS file
        run: |
          curl -o hustle-11u-temp.ics "https://api.team-manager.gc.com/ics-calendar-documents/user/9eeb60a3-c8fb-4fde-9f2c-a59e214e1109.ics?teamId=810f389e-3e8c-403b-83fa-54f652f45c37&token=${{ env.gc_token_11u }}"
      
      - name: Download 10U ICS file
        run: |
          curl -o hustle-10u-temp.ics "https://api.team-manager.gc.com/ics-calendar-documents/user/9eeb60a3-c8fb-4fde-9f2c-a59e214e1109.ics?teamId=33d5f1bd-0c63-4819-b5b3-f2008a434daf&token=${{ env.gc_token_10u }}"
      
      - name: Remove DTSTAMP from 11U ICS
        run: sed -i '/^DTSTAMP:/d' hustle-11u-temp.ics
      
      - name: Remove DTSTAMP from 10U ICS
        run: sed -i '/^DTSTAMP:/d' hustle-10u-temp.ics
      
      - name: Commit and push changes
        run: |
          update_needed=false
          if [ ! -f hustle-11u.ics ] || ! cmp --silent hustle-11u-temp.ics hustle-11u.ics; then
            echo "11U ICS file changed"
            mv hustle-11u-temp.ics hustle-11u.ics
            update_needed=true
          else
            rm hustle-11u-temp.ics
          fi
          if [ ! -f hustle-10u.ics ] || ! cmp --silent hustle-10u-temp.ics hustle-10u.ics; then
            echo "10U ICS file changed"
            mv hustle-10u-temp.ics hustle-10u.ics
            update_needed=true
          else
            rm hustle-10u-temp.ics
          fi
          if [ "$update_needed" = true ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add hustle-11u.ics hustle-10u.ics
            git commit -m "Update 11U and/or 10U ICS files"
            git push
          else
            echo "No ICS updates needed."
          fi
